### ISSUE TITLE
Deprecated message in log

### ISSUE THREAD

**Issue by fribse** [Tom-Hirschberger/MMM-MQTTbridge#11] opened 2021-01-01 09:42 UTC
Hi @sergge1 et al

It is still running rock solid here. The bathroom mirror is turned on and off together with the light in the bathroom, and it's working perfectly.

I've been sitting here doing some extra touches to the config, and I just noticed these messages in the log:

```
0|mm  | [2021-01-01 10:36:50.077] [LOG]    [MQTT bridge] Subscribed to the topic: cmnd/bathroom/mirror
0|mm  | [2021-01-01 10:36:51.646] [ERROR]
0|mm  | (node:7469) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
0|mm  | [2021-01-01 10:36:51.655] [ERROR]
0|mm  | (node:7469) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

```
I'm not sure how to tell if it's from the MQTT Bridge these messages?
But if they are, I just wanted to give a heads up, before they turn into error messages.
It's the latest version of MM and MMM-MQTTBridge.

**Comment by sergge1** [comment] 2021-01-03 21:14
@fribse  I will check later whether it is relate to the mqttbrdige or not. thanks for informing!

**Comment by Tom-Hirschberger** [comment] 2022-11-18 19:03
It looks like this was a problem caused by node in version 12 (could not find any other information). As the suggested node version for MagicMirror is 16 now and i do not see this warning in any of my setups i will close the issue

**Closed as completed by Tom-Hirschberger** 2022-11-18 19:03 UTC
